spring.application.name=Finance

spring.datasource.url=jdbc:mysql://localhost:3306/gastos
spring.datasource.username=root
spring.datasource.password=Ra@95114714

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
